# Generated by Django 2.2 on 2020-01-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('1', '行政区划'), ('2', '道路'), ('3', '村'), ('4', '人工建筑'), ('5', '自然实体')], max_length=1)),
                ('location', models.CharField(max_length=30)),
                ('coordination', models.CharField(default='a', max_length=21)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
