# Generated by Django 2.2 on 2020-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceinfo',
            name='choice_code',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
