# Generated by Django 2.2 on 2020-01-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='zone',
            field=models.CharField(choices=[('01', '鼓楼'), ('02', '台江'), ('03', '仓山'), ('04', '马尾'), ('05', '晋安'), ('06', '长乐'), ('07', '闽侯'), ('08', '连江'), ('09', '罗源'), ('10', '闽清'), ('11', '永泰'), ('12', '平潭'), ('13', '福清'), ('14', '古田'), ('15', '屏南')], max_length=2),
        ),
    ]
