# Generated by Django 2.2 on 2020-01-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coordination',
            field=models.CharField(max_length=21),
        ),
        migrations.CreateModel(
            name='sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_url', models.URLField()),
                ('sounder', models.CharField(max_length=10)),
                ('birthplace', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=4)),
                ('recorded_time', models.DateField()),
                ('sound_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='direct.Position')),
            ],
        ),
    ]
