# Generated by Django 2.2 on 2020-02-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='position',
            name='last_updated_time',
        ),
    ]
