# Generated by Django 2.2 on 2020-01-19 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_auto_20200119_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sound',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
