# Generated by Django 2.2 on 2020-02-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_auto_20200210_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coordination',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
