# Generated by Django 2.2 on 2020-01-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_choiceinfo_choice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_type', to='direct.ChoiceInfo'),
        ),
        migrations.AlterField(
            model_name='position',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_type', to='direct.ChoiceInfo'),
        ),
    ]
