# Generated by Django 2.2 on 2020-01-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0003_auto_20200119_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='sound_id',
            new_name='sound_position',
        ),
    ]
