# Generated by Django 2.2 on 2020-01-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0004_auto_20200119_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='sound_id',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
