# Generated by Django 2.2 on 2020-01-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0005_sound_sound_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='sound_id',
            field=models.CharField(max_length=9),
        ),
    ]
