# Generated by Django 2.2 on 2020-01-19 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0006_auto_20200119_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='sound_url',
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_id',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('photo_position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='direct.Position')),
            ],
        ),
    ]
