# Generated by Django 2.2 on 2020-01-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0007_auto_20200119_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='direct.ChoiceInfo')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='type_first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direct.ChoiceInfo'),
        ),
        migrations.AddField(
            model_name='position',
            name='type_second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choiceinfo', to='direct.ChoiceInfo'),
        ),
    ]
