# Generated by Django 2.2 on 2020-01-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0009_areainfo_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='type_third_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choiceinfos', to='direct.ChoiceInfo'),
        ),
    ]
