# Generated by Django 2.2 on 2020-01-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0010_position_type_third_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='heroinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='heroinfo',
            name='province',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='type_first_choice',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='choiceinfo',
            name='belong_to',
        ),
        migrations.RemoveField(
            model_name='position',
            name='type_second_choice',
        ),
        migrations.RemoveField(
            model_name='position',
            name='type_third_choice',
        ),
        migrations.AddField(
            model_name='choiceinfo',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='direct.ChoiceInfo'),
        ),
        migrations.AddField(
            model_name='position',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areainfo', to='direct.ChoiceInfo'),
        ),
        migrations.AddField(
            model_name='position',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areainfos', to='direct.ChoiceInfo'),
        ),
        migrations.DeleteModel(
            name='AreaInfo',
        ),
        migrations.DeleteModel(
            name='HeroInfo',
        ),
    ]
