# Generated by Django 2.2 on 2020-01-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0011_auto_20200121_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='province',
            new_name='type_first_choice',
        ),
        migrations.RemoveField(
            model_name='choiceinfo',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='position',
            name='city',
        ),
        migrations.RemoveField(
            model_name='position',
            name='country',
        ),
        migrations.AddField(
            model_name='choiceinfo',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='direct.ChoiceInfo'),
        ),
        migrations.AddField(
            model_name='position',
            name='type_second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choiceinfo', to='direct.ChoiceInfo'),
        ),
    ]
