# Generated by Django 2.2 on 2020-01-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0013_areainfo_heroinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroinfo',
            name='country',
        ),
    ]
